= Introducció

El 13 de setembre de 2007 té lloc a Girona una manifestació en protesta per la visita del monarca espanyol a la localitat catalana, sota el lema "_Els catalans no tenen rei_". Durant la manifestació, diverses persones cremen fotografies del rei. Dos d'elles, Jaume Roura i Enric Stern, són jutjades pel delicte d'injúries a la Corona i condemnades a 15 mesos de presó commutables per una multa de 2.700 euros #footnote("«Multa de 2.700 euros por prender fuego a fotos del Rey». El País. (21/11/2007)"). 

El judici s'ha de repetir perquè als enjudiciats se'ls nega el dret a declarar en català. En termes de Bourdieu podríem parlar de la violència simbòlica exercida per l'Estat mitjançant la qual s'intenta arrancar una conducta de submissió (no poder parlar la teua llengua) basada en una creença socialment inculcada @bourdieu_razones_2002. No obstant, una vegada repetit el judici, es confirma la mateixa condemna, malgrat que el fiscal rebaixa la qualificació a alteracions de l'ordre públic. Aquests fets varen motivar que l'Audiència Nacional es pronunciés quasi un any després i arribara a la conclusió que la crema de fotos del rei constitueix un delicte d'injúries a la corona castigat amb penes de 6 a 24 mesos de presó#footnote("«La Audiencia Nacional confirma que quemar fotos del Rey es un delito de injurias a la Corona». El País(06/11/2008)").

En juliol de 2007 es publicava una portada al setmanari El Jueves on apareixien caricaturitzats el príncep hereu Felipe de Borbón i la princesa Letizia Ortiz. Esta portada va motivar el segrest de la publicació, la prohibició de la seua venda, la confiscació dels motles i, inclús, el tancament de la pàgina web de la revista. El 14 de novembre del mateix any el jutge va declarar culpables al dibuixant, Guillermo Torres, i el guionista, Manel Fontdevila; d'un delicte d'injúries al príncep hereu i els condemna al pagament d'una multa de 3.000 euros.

Els successos relatats promogueren multitud de discursos als mitjans de comunicació. Com a persona que va seguir aquestes notícies a la premsa, em van interessar els diferents enfocaments de les notícies en els diferents mitjans, i em va fer preguntar-me quina influència tenien aquests discursos en el manteniment d'aquesta figura delictiva.

Aquests fets, juntament amb el segrest de la revista El Jueves, em varen motivar a la confecció del present treball, que té com a *objectiu* esbrinar quin és el mecanisme mitjançant el qual els discursos serveixen com a eina legitimadora de polítiques criminals restrictives de llibertats. És a dir, quins elements discursius estan afavorint la legitimitat del manteniment de penes molt greus per cremar un tros de paper amb la cara d'un monarca o per publicar una caricatura en una revista.

També hem de que tindre en compte, des d'un punt de vista epistemològic, que allò que ens interessa estudiar ve influenciat per la nostra història de vida. En el meu cas, vaig ingressar en la policia quan tenia 19 anys amb la vocació de defensar el lliure exercici dels drets i les llibertats dels ciutadans. Al llarg dels anys, i amb una història de militància política progressista, em vaig començar a revelar contra aquelles normes que considerava injustes, però que havia d'aplicar perquè així ho manava la llei. Llavors em vaig interessar en esbrinar perquè no es canviava la llei. Quins eren els mecanismes pels quals costava tant produir canvis promoguts des del contrapoder. Al present treball tractaré de donar un poc de llum al respecte del paper dels discursos en aquest mecanisme de legitimació, tenint també en compte que la meua perspectiva també estarà influenciada per la meua formació com a psicòleg social i criminòleg.

Malgrat que una anàlisi acurada de la influència dels discursos presentes als mitjans de comunicació hauria d'incloure premsa, ràdio, televisió i internet, criteris d'operativitat m'obliguen a acotar molt aquest treball, per això em centraré en l'anàlisi dels discursos al voltant dels fets de de la revista El Jueves presents a la premsa, en la seua versió digital.

L'interès del present estudi radica en detectar les pràctiques discursives de contingut polític presents als mitjans i més concretament, aquelles referides a la política criminal i al delicte d'injúries a la corona. Així, podrem comprovar si els partits polítics i els mitjans de comunicació afins, han adaptat els seus discursos als nous formats comunicatius, deixant enrere llargues retòriques, tempos lents, explicacions prolongades i pesats continguts ideològics @bouza_impact_2004. Estem, doncs, davant d'uns discursos més subtils, emprant plànols de significació en un nivell connotatiu en termes dels mites de #cite(<barthes_mythologies_2015>, form: "prose"), produint en el lector un efecte d'estar llegint una informació incontestable, ja que la lectura es fa a partir del nivell denotatiu. Així mateix, l'ús d'aquest nivell connotatiu transmet valors basats en representacions considerades evidents i serveix per a afermar el domini d'una ideologia @ollivier_les_2010.

La perspectiva des de la qual s'abordarà aquest treball és la de l'Anàlisi Crítica del Discurs (en endavant ACD), no en va és des d'una perspectiva crítica des d'on podem observar i analitzar pràctiques discursives al servei del manteniment de determinades institucions, com resulta del cas de l'ordre penal i del delicte d'injúries a la corona. El propi Bourdieu amb el seu concepte de _Habitus_, adverteix que els agents socials actuen com si l'univers social fora una cosa natural, ja que les estructures cognitives que s'utilitzen per interpretar el món naixen de la pròpia estructura d'aquest món (Fernández Fernández, 2005). És per això el meu interès per esbrinar els processos discursius de producció i manteniment d'aquest _Habitus_. En paraules de Fairclough, el que està en joc és el procés de classificació mitjançant el qual "_preconstruccions naturalitzades_" generen una "_visió_" particular del món @fairclough_analysing_2003. Per això crec que resulta interessant posar de manifest aquestes preconstruccions que eviten que ens qüestionem la visió del món que ens ve donada, i fa que per exemple, no ens qüestionem la legitimitat de polítiques restrictives de llibertats, com ho són les penes de presó previstes per fer una caricatura presumptament injuriosa d'algun membre de la família reial.

El present treball està estructurat de manera que començaré fent una introducció als discursos dins del que podríem anomenar comunicació política. Parlaré dels discursos com a mecanisme legitimador i de l'efecte dels mitjans de comunicació sobre la societat segons diverses corrents teòriques.

A continuació d'això, iniciaré al lector en determinats conceptes de la política criminal que resulten indispensables per a presentar el context. El context resulta un element imprescindible per a la interpretació dels discursos que presentaré a la part empírica d'aquest treball. Aquesta introducció del context consistirà en explicitar fenòmens com el de l'expansió del  dret penal en els darrers temps, i que s'ha començat a utilitzar per normativitzar comportaments que segons molts juristes deurien de quedar al marge del dret penal.

Seguiré per introduir el debat clàssic de llibertat vs seguretat, per en acabant parlar del dret penal simbòlic, entès com a aquell pretén regular aspectes morals, més enllà de fets objectius.

Veurem després algunes aportacions de la literatura sobre el dret penal de l'enemic, que és aquell que no s'aplica a la generalitat de persones, sinó només a aquells que es consideren "_enemics_" des d'un punt de vista del "_nosaltres_" vs "_ells_".

I finalment parlaré del Codi Penal espanyol en aquell articulat que afecta al delicte d'injúries a la corona.
La segona part del treball explicitaré la metodologia i les tècniques usades per a l'anàlisi d'aquests discursos i que anirà des de la justificació de la tria del corpus, a les tècniques i les variables que es tindran en compte des del prisma de l' ACD.

Finalment presentaré els resultats de l treball, i ho faré seguint un esquema proposat per #cite(<alamo_alisis_2009>, form: "prose"), que facilitarà la comprensió de la totalitat del corpus i el posterior treball sintètic que constituirà ja l'apartat de conclusions.

Com a complement al treball, s'inclourà un apartat de discussió, on es tractarà tot allò que es considere interessant respecte a aquest treball, tant sobre el fons de la qüestió, com sobre aspectes operatius o metodològics, així com aquells aspectes que es considere que es poden millorar o ampliar en posteriors treballs.

== Comunicació política

Coincidint amb l'establiment de la democràcia com a forma de govern, en la Grècia del segle V aC, la retòrica apareix com la forma que ha de prendre un discurs per a convèncer. La presa en consideració d'aquesta propietat del llenguatge ha contribuït a renovar l'interès que ja va mostrar Aristòtil per la retòrica, i despertar la sensibilitat cap als efectes sociopolítics i psicològics que emanen de les diferents pràctiques discursives, especialment dels discursos amb efectes estigmatitzants. L'interès mostrat per l'estudi dels discursos ha permès evidenciar, no només les estratègies discursives pròpies de cada tipus de discurs, sinó que també ha permès evidenciar els artificis retòrics que s'utilitzen per a crear diverses realitats @rueda_alisis_2011.

Però no només la retòrica té interès des del punt de vista de l'anàlisi del discurs i dels efectes de les pràctiques discursives, també tenen importància altres aspectes del discurs com ara la identificació de les posicions discursives, les configuracions narratives i els espais semàntics @alamo_alisis_2009, que desenvoluparé a l'apartat de metodologia.

Parlem de comunicació política i no d'un altra comunicació, perquè malgrat que els principis fonamentals de la comunicació són extensibles a totes elles, aquesta té de particular que es mou dins del camp de la política i per tant fa ús d'una semàntica pròpia del seu camp.

Amb els discursos es posen de manifest les ideologies subjacents d'una manera més o menys explícita. Això ens permet estudiar-los fent us de textos i d'altres formes de discurs tangibles i analitzables. Encara que hem de tindre en compte que les ideologies també són observables no només en la comunicació política sinó també en les pràctiques polítiques, però que d'una manera més implícita @van_dijk_politica_2005, com per exemple la ideologia de la discriminació es manifesta en determinades polítiques que retallen drets a les persones immigrants.

=== Els discursos com a mecanisme legitimador

Cal primer, distingir entre text i discurs. El propi #cite(<ibanez_mas_1992>, form: "prose") conceptualitza el text com la matriu ideològica que es troba a la base d'alguns discursos. Jo em referiré al text atenent al seu significat literal, és a dir,  "_ Contingut d'un  escrit, les pròpies paraules d'un autor (...) _", tal i com apareix a la primera accepció del Diccionari de l'Institut d'Estudis Catalans (DIEC2), en contraposició al concepte discurs, que tractaré de definir a continuació.

Existeixen nombroses definicions de "_discurs_", però de totes elles podem extraure que el discurs va més enllà del text. Podríem dir que el text no és més que un dels suports visibles del discurs. "_Els discursos -tinguts en compte com a maneres de parlar, escriure i, en general, d'expressar que porten als participants de qualsevol situació comunicativa a adoptar determinades actituds davant àmbits de l'activitat sociocultural_" @basil_teoritraduccion_1995.

En termes analítics, vaig a considerar els discursos d'acord amb la concepció que proposa #cite(<alamo_alisis_2009>, form: "prose"): "_El Discurs és l'elaboració teòrica realitzada per l'equip d'investigació a partir de l'anàlisi de textos produïda en aquesta_". Això significa que les meues conclusions al present treball, també seran "_el discurs_",si més no, el discurs que jo com a investigador interessat en respondre a les meues preguntes d'investigació, he elaborat a partir dels textos del corpus.

Són nombrosos els estudis sobre el paper que juguen els discursos en la transmissió persuasiva i en la legitimació d'ideologies, i valors. De manera que és habitual trobar-se discursos autoritzats que ens indiquen allò que és "_normal_" o sobre allò que és important o essencial i allò que és prescindible o accessori @martin_rojo_alisis_2012 . Per tant resulta interessant esbrinar qui o què determina que un discurs és autoritzat o legitimitat, mentre que d'altres són considerats marginals o "_antisistema_". Per exemple, per què es considera "_antisistema_" un discurs que postula la necessitat de tornar a un "_sistema_" republicà? O, dit d'una altra manera, perquè cada vegada que algú proposa un canvi de sistema se li diu "_antisistema_"? La resposta, com bé diu Rojo, la trobem en els discursos autoritzats vs discursos desautoritzats.

La legitimació, doncs, comença per limitar l'accés als canals de difusió massiva, per a que només accedisquen els discursos autoritzats. Tal i com feien els antics oradors de la polis, hui, novament la paraula s'ofereix al públic. Però aquesta vegada a milions d'espectadors. La televisió reprodueix en directe els enfrontaments verbals introduint així les pràctiques ancestrals d'oradors i sofistes sota la tutela de professionals de l'escena @dorna_estudios_1993.

 Aquestes pràctiques discursives tenen efectes sobre el manteniment i reforç de l'ordre social i el manteniment de l'statu quo , no només pel fet de circular per canals privilegiats i autoritzats, sinó perquè al mateix temps impedeixin la circulació de discursos que són dissonants amb el poder. D'aquesta manera, els grups minoritaris i/o minoritzats tenen molt limitat l'accés als grans mitjans de comunicació i tendeixen a usar canals alternatius de transmissió per als seus missatges, com ara mitjans digitals amb un disseny més horitzontal com per exemple la xarxa social Twitter.

Els rituals dels que parla #cite(<durkheim_formas_2021>, form: "prose") cobren rellevància en el tema tractat al treball, en tant que podem extrapolar els rituals religiosos que descriu Durkheim a d'altres rituals pagans, de tal manera que podríem considerar l'acte de cremar fotos en públic, o dibuixar una caricatura burlesca com un ritual. Un ritual de protesta contra un règim amb el qual no s'està d'acord i al qual no se li dona ni la cobertura ni el tractament mediàtic que reben altres rituals "_autoritzats_". Resulta interessant analitzar el tractament que es fa als mitjans d'un ritual que va en contra del sistema establert.

Els mitjans de comunicació de masses resulten de capital importància en els nostres temps per a la difusió de rituals. Així, tenim rituals que són transmesos en temps real a bona part del globus, com ara Les Jornades Mundials de la Joventut. "_Aquestes retransmissions augmenten el nombre de participants i reforcen el lligam identitari_" @ollivier_les_2010, en aquest cas el religiós.

Però no només rituals religiosos són transmesos a través dels mitjans de comunicació. Un gran nombre de rituals seculars tenen gran difusió i seguiment, com ara retransmissions esportives, on l'individu participa activament dels rituals des de la seua pròpia casa. Uns rituals que depassen allò individual per convertir-se en un fe t col·lectiu. Per això l'interès que poden tindre les institucions que estan al poder per fer que els rituals de contrapoder siguen deslegitimats i no siguen difosos, i en canvi promouen la difusió de rituals "_innocus_", com ara esdeveniments religiosos o esportius.

=== La persuasió

Si aquest treball té alguna vocació pràctica, aquesta és la de provocar el debat sobre cóm ens afecten els missatges polítics que rebem i fer que siguem conscients dels mecanismes que actuen per tal de contrarestar-los i fomentar l'esperit crític. Un dels mecanismes que estan a la base d'aquest canvi d'actitud és la persuasió, per això he cregut adient fer una pinzellada sobre aquest mecanisme.

La psicologia social ha tractat el tema de la persuasió d'una manera àmplia. Podem distingir dos grans enfocaments al respecte. L'enfocament tradicional i un enfocament més modern de caire cognitiu. L'enfocament tradicional és el que suporta una major literatura i prové del període immediatament posterior a la II Guerra Mundial. Amb aquest enfocament es tracta el tema de la comunicació persuasiva tenint en compte uns components bàsics, a saber:

- La font del missatge persuasiu.
- L'estructura i el contingut del missatge.
- El mitjà pel qual es transmet el missatge.
- L'audiència/receptors del missatge persuasiu.
Per tant, des d'aquesta perspectiva se'ns presenta la persuasió des de l'esquema clàssic "_Qui diu què a qui, per quin canal i amb quins efectes?_" és a dir, un comunicador o font que presenta un missatge servint-se d'un mitjà a una audiència. A aquest esquema afegim tot allò que ocorre dins del context social.

L'enfocament tradicional ha tingut una utilitat innegable durant dècades (com ara la credibilitat de la font o algunes característiques del receptor), i va proporcionar molta informació sobre el quan és més probable que ocórrega el canvi d'actitud i com pot ser produït. Però no ens aturarem ara a analitzar l'ampla literatura sobre aquestes tesis i sí que paga la pena aturar-nos un moment a analitzar les darreres aportacions de l'enfocament cognitiu.

A l'enfocament cognitiu no es pregunta "_Qui diu què a qui per quin mitjà i amb quin efecte?_" sinó "_Quins processos cognitius determinen que algú siga efectivament persuadit?_". En concret tracta d'entendre què pensen les persones quan estan exposades a missatges persuasius i cóm aquests pensaments i processos cognitius rellevants determinen si les persones experimenten un canvi d'actitud i en quin grau ho fan @baron_psicologisocial_1998. Dit d'una altra manera, la proposició central de l'enfocament cognitiu de la persuasió consisteix en que la probabilitat de que el missatge efectivament persuadisca a algú depèn de com la persona processa el missatge. Podem destacar dos models cognitius més importants de la persuasió:

- El model de probabilitat d'elaboració de Petty i Cacioppo i
- El model heurístic-sistemàtic de Chaiken.

En ambdós models es planteja que les persones processen la informació  sobre objectes actitudinals de dos maneres diferents. La poden revisar de manera superficial o poden considerar-la d'una forma més sistemàtica. Quan les persones es decanten pel processament superficial, es basen en la informació que tenen més accessible per a realitzar inferències sobre l'objecte actitudinal i aquestes són més bé simples. En canvi, quan usen el processament sistemàtic, van més enllà de les claus simples i tenen en compte la força dels arguments i les seues implicacions per a l'avaluació de l'objecte actitudinal. En ambdós casos es pot produir el canvi d'actitud però per camins diferents.

Tot açò pot resultar interessant per a entendre quins tipus de processament de la informació poden fer servir els lectors d'un diari, i per tant a quin tipus de missatge persuasiu seran més vulnerables.

D'acord amb Petty i Cacioppo, quan una persona rep un missatge persuasiu, pensa en el missatge, en els arguments que conté, i al mateix temps, en els arguments que no apareixen. I són aquests pensaments i no el missatge mateix, els que acabaran per conduir al canvi.

Així, d'acord amb el model de probabilitat d'elaboració, existeixen dues rutes diferents que donen compte del diferent grau d'esforç cognitiu necessari per part del receptor del missatge.

Quan els missatges persuasius es refereixen a temes que són importants per al receptor, és probable que aquest li dedique una atenció major al missatge i als seus arguments. En aquest cas la persuasió té lloc mitjançant el que es coneix com la ruta central. Es tracta d'una manera curosa de processar el missatge, on s'avaluen amb força i racionalitat els arguments, es veu la seua consistència amb els coneixements previs sobre el tema, es generen contra-arguments, es comparen els arguments presentats amb els contra-arguments, i s'arriba a una conclusió general. Quan els arguments són processats mitjançant aquesta ruta central, només es produirà canvi d'actitud en la mesura en que els arguments presentats siguen convincents i presenten suficients evidències.

En canvi, quan els missatges es refereixen a temes menys importants personalment per al receptor, l'individu no s'involucra amb tot l'esforç cognitiu que suposa la ruta central. En aquest cas la persuasió té lloc mitjançant el que es coneix com la ruta perifèrica. És un tipus de processament que es dóna quan la persona no té la motivació o la capacitat per a processar sistemàticament la informació. Quan açò té lloc entren en joc les claus perifèriques de la persuasió, que són aspectes referits a la font del missatge (prestigi, credibilitat, atractiu,...) o a l'estil i a la forma del missatge.

La idea central del model de probabilitat d'elaboració, és que els receptors de la comunicació persuasiva segueixen la ruta central quan les diferents variables situacionals i individuals asseguren una motivació alta i una capacitat per a l'elaboració, açò és, per a la generació de pensaments i reaccions favorables i desfavorables al contingut del missatge. En canvi, els receptors segueixen la ruta perifèrica quan la motivació o la capacitat (o ambdues) per a l'elaboració són baixes @eagly_uneven_1992.

S'ha de tindre en compte que ambdues rutes representen els extrems d'un continu, i que en ambdós casos pot haver persuasió, però la naturalesa del procés persuasiu és diferent en cada cas. Si tenim en compte aquest continu, es pot pensar que amb nivells moderats de probabilitat d'elaboració, el procés de persuasió pot representar una interacció o una complexa combinació d'ambdós tipus de processament @eagly_uneven_1992 .

L'altre model del que parlava era el de model heurístic-sistemàtic de Chaiken @eagly_uneven_1992, també conegut simplement com a heurístic. Aquest model també postula dos vies per a la persuasió, d'una manera similar al model de probabilitat d'elaboració. El processament sistemàtic es correspon amb el que hem anomenat en l'anterior model com a ruta central, en canvi la ruta perifèrica al model heurístic se centra especialment en les regles simples de decisió que utilitzen els receptors d'un missatge per a jutjar la seua validesa @eagly_uneven_1992.

Chaiken focalitza la seua atenció en la distinció (basada en la psicologia cognitiva) entre un algoritme i un heurístic, dos tipus diferents de regles que podem usar per a resoldre un problema. Un algoritme és una regla sistemàtica que, si se segueix al peu de la lletra, ha de conduir a la solució del problema. En canvi, podríem dir que un heurístic és una regla simple de decisió que algunes vegades serveix i altres no.

En el camp de la persuasió un heurístic és una regla simple que permet a les persones avaluar un objecte en base a les seues característiques més superficials, és a dir, decidir si els agrada o no els agrada alguna cosa sense tindre en compte la informació disponible amb una major profunditat.

Quan el missatge té a veure amb actituds importants per a la persona, té lloc un processament sistemàtic de la informació, en canvi quan la involucració personal és més bé baixa, els individus utilitzen diversos heurístics per a determinar si canvien o no les seues actituds. D'eixa manera, s'ha demostrat que les persones són més fàcilment persuadides per fonts expertes que no expertes, més per fonts atractives que per no atractives, més quan major és el nombre d'arguments emprats i més amb arguments recolzats per estadístiques que per aquells que no ho estan @baron_psicologisocial_1998.

Podem afirmar aleshores que en nombroses ocasions la persuasió no és el resultat d'una anàlisi de la validesa del missatge, ans al contrari ho és de l'efecte d'alguna clau perifèrica del missatge (com ara la longitud o el nombre d'arguments), de la font (per exemple l'experiència aparent de l'emissor o l'atractiu), o de les reaccions d'altres persones al missatge (com per exemple el consens).

=== Poder i influència social
El poder és una forma de control sobre les persones. Podem considerar els processos d'influència social com als mecanismes que tracten d'aplicar aquest poder per influir en la gent. Per a posar un poc de llum sobre aquests processos parlaré sobre les bases del poder social per a després introduir conceptes com el de conformitat o manipulació.

En primer lloc valent-nos de la concepció de #cite(<dijk_poder_1993>, form: "prose"), direm que quan parlem ací de poder, ens referim al poder social, i especialment a l'abús de poder.

 Podem distingir entre influència i poder en el sentit de que la *influència* es refereix al resultat d'una interacció en la qual una persona canvia algun aspecte de la seua conducta en la direcció intentada per un altra; mentre que poder es refereix a la força que motiva aquest canvi @dijk_poder_1993. Dit d'una altra manera, influència es refereix a l'estat final, mentre que *poder* es refereix als mitjans usats per a aconseguir eixa finalitat.

La influència social també la podríem definir com un canvi de creences, actituds, conducta o emocions d'una persona, provocat per una altra persona, mentre que el poder social seria la influència potencial. La persona que és font de la influència s'anomena *agent* i la persona receptora s'anomena *objecte*. Per tant, per sintetitzar, podem dir que el poder social és la capacitat que té un agent d'influència per a afectar a algun objecte.

Per tractar de situar quina classe de poder exerceixen els discursos presents als mitjans de comunicació, farem una breu introducció als diferents tipus de poder. Una de les taxonomies de poder més àmpliament acceptades és la que proposaren en #cite(<french_bases_1959>, form: "prose"), que distingeix entre poder expert, poder referent, poder legítim, poder de recompensa i poder coercitiu. I a més a més és interessant també l'anomenat poder d'informació o informacional que Raven va introduir posteriorment i que veurem en primer lloc.

El *poder d'informació* és l'únic socialment independent dels altres tipus de poder, ja que estem parlant d'una influència merament informativa, on allò realment crític és el contingut del missatge. Aquest tipus de poder es deriva de la capacitat de l'agent de proporcionar informació a l'individu que el convença de que el canvi invocat és realment apropiat i convenient, per tant el seu efecte depèn del grau de convenciment dels arguments i de les evidències presentades.

Com a resultat d'aquest tipus de comunicació persuasiva, es produeix un canvi cognitiu en el receptor del missatge, i una vegada produït el canvi, aquest arriba a ser completament independent de l'agent que el va introduir. Podríem dir que el canvi es produeix en la via central de processament de la informació, on allò important és la qualitat dels arguments més que altres claus perifèriques com les característiques de la font o de l'agent. Un exemple d'influència d'informació seria un professor explicant un mètode millor per resoldre un problema matemàtic.

El *poder expert* és un tipus de poder que depèn de l'agent. Opera quan l'objecte d'influència atribueix a l'agent coneixements, capacitat o experiència superiors en el tema en el qual s'està intentant influir. Per exemple, seguir les recomanacions del metge o del teu advocat.

El *poder referent* és aquell que opera quan l'objecte d'influència s'identifica amb l'agent, bé perquè té alguna cosa en comú o bé perquè vol semblar-se a ell. És a dir, depèn de la identificació amb l'agent, o si més no, al desig d'identificació amb aquest. Quant major siga l'atracció o la identificació amb l'agent, major serà el poder de referència d'aquest.

El *poder de referència*, per tant, pot ser exercit per persones amb les quals no tenim una relació directa, com ocorre amb les persones que admirem (actors, esportistes, periodistes ...). Per això és un tipus d'influència a tindre en compte quan parlem d'articles periodístics, sobretot quan aquests provenen d'articulistes als quals admirem.

També pot existir una influència referent negativa, en que la persona adopta una actitud oposada a aquella que manté l'agent al que ha avaluat negativament, i amb el qual no es vol identificar. Aquesta influència referent negativa no es previsible que es done massa en el cas dels lectors de periòdics, ja que aquests tendeixen a llegir periòdics la ideologia dels quals encaixa amb la del lector.

El *poder legítim* és el que emana dels valors internalitzats per l'objecte d'influència i li donen a l'agent un "_dret legítim_" a influenciar-lo. Aquest poder té a veure amb el concepte d'autoritat i amb els rols socials.

El poder legítim pot estar basat en valors culturals com ara l'edat, en l'acceptació de l'estructura social com per exemple les organitzacions formals, i al mateix temps en l'acceptació d'una autoritat superior legítima o un líder triat pel grup.

Un aspecte interessant del poder legítim és el seu rang d'aplicació. Açò vol dir que aquest poder només és aplicable dins del seu àmbit de legitimitat ja que si es tracta d'aplicar més enllà d'ell, pot produir un efecte contrari. Podem posar l'exemple d'un líder eclesiàstic instaurant normes sobre la seua religió, i en canvi si aquest líder eclesiàstic tracta de fer valdre el seu poder sobre la societat civil, aquesta pot no acceptar la legitimitat del seu poder.

El *poder de recompensa* es caracteritza per ser altament depenent de l'agent d'influència, fins al punt de requerir que l'agent mantinga una vigilància per a assegurar-se que l'objecte manté el seu canvi d'actitud. Com el seu nom indica aquest poder es basa en la capacitat de l'agent per proporcionar recompenses per a la persona que està sent objecte de la influència. Les recompenses poden ser de molts tipus, des de les impersonals (diners, bona nota en un examen, una recomanació per un ascens,...) a les personals (aprovació, acceptació, amor,...).

Per últim tenim el *poder coercitiu*. Aquest poder deriva de la capacitat de l'agent d'influència de castigar a la persona que està sent influenciada, on per suposat es produirà el càstig si l'objecte no accedeix a ser influenciat. Es tracta també d'un poder altament depenent de l'agent, i per tant podríem dir que està socialment mantingut. Requereix per tant que l'agent mantinga una vigilància del compliment del canvi d'actitud, per tal d'aplicar el càstig si aquest no es porta a terme. També podem distingir entre càstigs impersonals (una mala nota, una multa, una detenció,...) i personals (desaprovació, rebuig, desafecció,...).

Aquests dos darrers tipus de poder (promesa de recompenses, i amenaça de càstigs) són considerats molt a sovint com a sinònims del concepte de poder, i per tant com a tècniques altament efectives d'influència. En canvi, tal i com ja he dit anteriorment, aquest s tipus de poder poden ser considerats menys eficaços que per exemple el poder d'informació, ja que tant el càstig com la recompensa requereixen de la intervenció constant de l'agent, malgrat que és cert que en alguns casos la vigilància pot ser mantinguda molt fàcilment, en molts altres pot resultar molt difícil o inclús impossible.

De tot l'exposat anteriorment podem concloure que els sis tipus de poder difereixen en diversa mesura. El poder d'informació és pràcticament independent de l'agent, ja que està basat en el contingut mateix de la comunicació i en el canvi a nivell cognitiu que es produeix. En canvi, els altres cinc tipus de poder són el que podríem anomenar socialment depenents, ja que impliquen que la persona continua relacionant la nova creença, conducta o actitud amb l'agent d'influència. D'aquests cinc poders socialment depenents, el poder de recompensa i el poder coercitiu es diferencien dels altres en que, per a ser efectius, requereixen que l'agent d'influència mantinga la vigilància.

Una vegada vistos els diferents tipus de poder, convé revisar altres processos que  modulen els nivell d'influència social que es pot exercir sobre la gent i d'eixa manera ens ajudarà a entendre millor com poden influir els discursos en l'actitud i el comportament de la gent, en el cas que ens ocupa envers la corona i el delicte d'injúries a la corona. Per això parlaré breument sobre el concepte de conformitat.

Entenem per *conformitat* aquelles pressions que sentim per comportar-nos de manera similar a altres persones del grup o en la societat en general. Els experiments clàssics de  Muzafer Sherif i de Solomon Asch demostren que la gent és capaç d'acceptar una resposta manifestament errònia com a correcta en pro del consens i de cedir a l'opinió majoritària del grup @smith_social_2014. Les persones ens conformem a les normes dels nostres grups la major part del temps, i ho fem principalment per dos necessitats universals: el desig d'estar en allò correcte i el desig de ser acceptat pels altres. En base a aquests desitjos podem distingir entre influència social informativa i influència social normativa.

La influència social informativa és aquella influència que ens fa acceptar la informació obtinguda d'altres com a una evidència extreta directament de la realitat. El "_saber que altres comparteixen la nostra visió, augmenta els nostres sentiments de mestratge, la nostra confiança en que les nostres opinions són correctes i la nostra resistència a la persuasió. Quan la conformitat a les normes del grup satisfà les nostres necessitats de mestratge perquè creiem que aquelles normes són correctes, el grup té una influència informativa_" @smith_social_2014.

La influència social normativa és  aquella que ens fa conformar-nos a les expectatives positives dels altres per a, d'eixa manera, obtindre la seua acceptació o com a mínim, evitar el rebuig. Quan les persones s'incorporen a un grup van aprenent, mitjançant instruccions formals o informals, o simplement per observació, tot un seguit de normes socials. Quan adoptem eixes normes com a pròpies estem demostrant el nostre compromís i el nostre orgull de ser com som i de pertànyer al nostre grup. Aleshores, "_quan ens conformem per a obtindre una identitat social positiva i arribar a ser membres valorats d'un grup que ens interessa, és a dir, satisfer les nostres necessitats de pertinença, el grup exerceix una influència normativa_" @smith_social_2014.

Existeixen diferències des del punt de vista de la cultura. En aquelles societats amb un al t potencial de creixement (caracteritzades per una alt nombre de naixements i de  morts, i per tant amb ràpid canvi generacional), la conformitat està assegurada per la tendència a seguir la tradició.

Les societats de creixement transicional (alt nombre de naixements, baix nombre de morts), desenvolupen en els seus membres una conformitat basada en l'adquisició d'un conjunt de metes internalitzades.

I aquelles societats que estan en l'etapa de declinació demogràfica incipient (baix nombre de naixements i de morts) desenvolupen en els seus membres una conformitat basada en la tendència a ser sensibles a les expectatives i experiències dels altres @smith_social_2014.

Per tant, segons el tipus de societat podem dir que tindrem individus dirigits per la tradició, internament dirigits o dirigits pels altres. Segons #cite(<riesman_muchedumbre_1964>, form: "prose"), els individus de les generacions anteriors eren més internament dirigits, en el sentit de que determinaven en major mesura els seus valors i les seues metes. En canvi les noves generacions s'orienten cada vegada més cap els seus parells per a determinar la seua conducta, pel que en gran mesura la seua conformitat es relaciona més amb les pressions externes.

No obstant això, autors com @myers_psicologia_2014 afirmen que la major o menor conformitat a les pressions externes en una societat, està directament relacionada amb el caràcter col·lectivista o individualista de la seua cultura. És a dir, que les cultures occidentals (i tenint la cultura dels EUA com a màxim exponent, i en menor mesura també Europa) serien considerades com a més individualistes, mentre que les asiàtiques i altres tindrien una caràcter més col·lectivista.

També resulta interessant fer una incursió al concepte de *manipulació*, ja que quan parlem d'anàlisi crítica del discurs, aquesta és una dimensió fonamental. La manipulació és una pràctica comunicativa interaccional, en la que el manipulador exerceix control sobre altres persones, generalment en contra de la seua voluntat o dels seus interessos @van_dijk_discurso_2006. Per tant la manipulació té una clara connotació negativa, sense la qual estaríem parlant de persuasió (legítima). La diferència fonamental radica en que en la persuasió els interlocutors són lliures de creure o actuar com els vinga en gana, segons si accepten o no els arguments de l'agent, mentre que en la manipulació els receptors tenen un  paper més passiu. Açò ocorre quan el receptor és incapaç de veure les intencions de l'agent amb el seu discurs manipulador o les conseqüències que pot tindre cedir a les creences o accions defensades pel manipulador.
Aleshores, podem entendre la manipulació com un element del concepte de (abús de) poder, entès com a un tipus de control que alguns agents o grups socials exerceixen sobre altres @dijk_poder_1993 . Aquest control, es refereix a un control de la cognició, de les creences, però indirectament també ho és de les accions. El tipus de manipulació social que ens interessa a efectes d'aquest treball és aquella que es defineix en termes de dominació social i la seua reproducció en pràctiques quotidianes, incloent el discurs @van_dijk_discurso_2006. Són, per tant, pràctiques discursives dels grups dominants dirigides cap a la reproducció del seu poder.

=== La influència del mitjans de comunicació

Des d'un punt de vista de la manipulació, tal i com l'hem conceptuada anteriorment, els mitjans de comunicació són un mitjà que es pot emprar per a exercir aquesta manipulació @van_dijk_discurso_2006.

Per a estar en condicions de manipular a molta gent es necessita tindre accés a alguna forma de discurs públic, com ara  les notícies. Per a exercir aquest poder es requereix accés a una sèrie de recursos socials escassos i un d'aquests recursos és l'accés preferencial als mitjans de comunicació i al discurs públic, un privilegi que comparteixen el que es coneix com a "_elits simbòliques_" (polítics, periodistes, científics, escriptors, professors,...) @van_dijk_discurso_2006.

Des de les teories funcionalistes de la comunicació s'apunta que els mitjans de comunicació són utilitzats pels poders públics per a les seues pròpies finalitats. En un esquema clàssic proposat per #cite(<laswell_structure_1948>, form: "prose") tot acte de comunicació pot ser analitzat mitjançant les preguntes Qui diu què, per mitjà de quin canal, a qui i amb quins efectes. Malgrat això les teories funcionalistes han estat criticades perquè simplifiquen el paper dels destinataris del missatges a simples receptors que no fan altra cosa que reaccionar a estímuls. Per això autors com #cite(<de_moragas_sociologicomunicacion_1985>, form: "prose") manifesten que aquestes teories sobrevaloren els efectes de les tècniques sobre el públic, als quals atorguen el paper de receptor passius. De la teoria hipodèrmica derivaran aquestes tesis funcionalistes i tindran el seu major exponent en els estudis de la influència de la propaganda durant la Primera Guerra Mundial. Aquestes tesis se sostindran amb l'auxili de la psicologia conductista, basada en un paradigma mecanicista estímul-resposta.

No falten, però, autors que sostenen la influència dels mitjans de comunicació de masses sobre el pensament col·lectiu. @halbwachs_conscience_2002 #footnote("sovint passa que ens atribuïm a nosaltres mateixos, com si només tingueren la seua font en nosaltres, idees i reflexions o sentiments i passions, que ens han estat inspirades pel nostre grup. Aleshores ens avenim tant amb aquells que ens envolten que vibrem a l'uníson i ja no sabem on es troba el punt de partida el punt de partida de les vibracions, si en nosaltres o en els altres. Quantes vegades expressem, amb una convicció que sembla ben personal, reflexions extretes d'un periòdic, d'un llibre o d'una conversació! Aquestes responen tan bé a les nostres maneres de pensar que ens sorprendria descobrir qui n'és l'autor i que no ho son nosaltres. Afirma que en moltes ocasions reproduïm arguments i idees que hem llegit a la premsa, i les atribuïm a nosaltres mateixos").

La corrent coneguda com a teoria dels efectes limitats @lazarsfeld_medios_1971 vindria a abundar en la idea de que se li havien atribuït als mitjans de comunicació uns poders que no tenien en realitat, i obriran una etapa que relativitzarà la influència dels mitjans en el públic. Així Lazarsfeld proposa una taxonomia d'efectes distingint entre efectes immediats, a curt termini, a llarg termini i institucionals. A més a més, en la seua anàlisi introdueix un segon eix que modularia aquests efectes limitats. En ell proposa que les causes d'aquestes efectes limitats poden ser un esdeveniment (com per exemple un programa de ràdio), el gènere (per exemple informatiu), l'estructura social i econòmica del mitjà de comunicació (sector públic o privat) i/o la naturalesa tècnica del suport (paper, imatge, so,...) @lazarsfeld_radio_1940.

Una de les aportacions més importants d'aquest autor al camp objecte d'estudi en aquest treball és la recerca dels processos que permeten produir i mantenir la legitimitat a una classe social o a un grup i, en concret, quins són els que permeten obtenir opinions i accions d'acord amb els seus interessos emprant la comunicació de masses, mitjançant metodologia quantitativa amb l'ús d'enquestes d'opinió @lazarsfeld_peoples_1968. Una de les conclusions més importants d'aquest estudi és que resulta fonamental la comunicació interpersonal, i en concret el paper dels líders d'opinió sobre la conducta de vot, per damunt del paper i la influència dels mitjans de comunicació. Altra conclusió del treball de Lazarsfeld és que els mitjans de comunicació serveixen per cristal·litzar opinions existents, més que no per a produir un canvi @lazarsfeld_peoples_1968.

Per això és previsible que els missatges presents a la premsa, s'adaptaran a la ideologia del seu públic potencial, de tal manera que els periòdics conservadors transmetran missatges conservadors i els periòdics progressistes inclouran missatges progressistes, altrament es produiria una reactància en el lector degut a les expectatives creades en aquest pel que s'ha denominat el contracte de lectura @veron_postface_1973. En paraules d'#cite(<ollivier_les_2010>, form: "prose") "_El contracte de lectura és un contracte implícit que lliga el periòdic amb els seus lectors. Es basa en les expectatives del lector i implica que el mitjà construirà el seu lector model per poder trobar el seu lector empíric i crear-hi un clima de confiança_".

El contracte de lectura resulta d'utilitat en l'anàlisi de premsa, en tant en quant ens permet estudiar el posicionament del mitjà de comunicació. Així doncs, podem tractar de localitzar al text marques de l'enunciació que ens indicaran si estem davant del que Ollivier anomena un enunciador palès, o estem davant d'un enunciador ocult. Ens permetrà, així mateix, distingir si el discurs es presenta com a verídic (en tercera persona), si es presenta com un discurs de caire pedagògic (manifestat per l'oposició nosaltres/vosaltres i que propugna consells) o com un discurs de complicitat (amb l'ús d'imperatius, dirigint-se directament al lector,...). "_En la gran part dels casos, el discurs es presenta com si mostrara alguna cosa, com si el lector veies la realitat mateixa i intentés dissimular el seu procés d'enunciació_" @ollivier_les_2010.

== El context: la política criminal

=== L'expansió del Dret penal

Durant els anys 80 del segle passat, es va instaurar a Europa una corrent doctrinal en favor d'un "_Dret penal mínim_". Podem pensar que eixe era el pas lògic a una progressiva reducció del poder punitiu a allò estrictament necessari. En canvi, la realitat de les polítiques criminals europees es va encaminar en sentit contrari, de tal manera que la majoria de les reformes penals han anat orientades a ampliar l'abast del Dret penal @corcoy_bidasolo_limites_2004.

Autors de l'Escola de Frankfurt, encapçalats per Hassemer, denuncien l'adopció del Dret penal com una eina quotidiana de resolució de conflictes. És el que anomenen soft law, que converteix el Dret penal en "_simbòlic_" @hassemer_derecho_1995. El postulat d'aquesta corrent dogmàtica del Dret penal advoca per que aquest se centre en la protecció de béns jurídics individuals i quan ho fa en béns jurídics col·lectius, aquests han de tindre el seu referent en un bé jurídic individual. Altrament el Dret penal simbòlic es correspondrà amb la representació d'inseguretat global en una societat del risc, en termes de Beck,  i tindrà una funció d'engany.

Pocs són els autors que s'han posicionat en contra de reformes penals que vulneren clarament principis com el d'igualtat o el de proporcionalitat, com ara la introduïda per la L.O. 7/2003 #footnote("Llei Orgànica 7 / 2003, de 30 de juny, de mesures de reforma per al compliment íntegre i efectiu de les penes"), 11/2003 #footnote("Llei Orgànica 11/2003, de 29 de setembre, de mesures concretes en matèria de seguretat ciutadana, violència domèstica i integració social dels estrangers") i 15/2003 #footnote("Ley Orgánica 15/2003, de 25 de noviembre, por la que se modifica la Ley Orgánica 10/1995, de 23 de noviembre, del Código Penal") @corcoy_bidasolo_limites_2004 . A més a més, com indica Mirentxu Corcoy (2004) s límits de caràcter axiològic, com són el respecte al principi d'intervenció mínima i última ratio . Per tant resulten, difícilment legitimables, des d'un punt de vista objectiu,  aquelles polítiques dirigides a incrementar l'abast d'actuació del Dret penal cap a delictes de caràcter simbòlic, com ara cremar una foto, una bandera o fer una caricatura del monarca.

#cite(<silva_sanchez_expansion_1999>, form: "prose") postula que l'actual Dret penal implica l'existència de ciutadans de primera i de segona. En el primer cas tenim aquells delictes que només poden cometre els poderosos (delictes fiscals, malversació, corrupció, ...) en el qual els corrents dogmàtics actuals postulen que aquests tipus de delictes no deurien castigar-se amb penes privatives de llibertat. I d'altra banda tenim el Dret penal nuclear, on figuren aquells delictes que podem cometre la resta de ciutadans.

#cite(<prittwitz_derecho_2004>, form: "prose") inclou una tercera classe de ciutadans (de tercera), i són aquells afectats pel denominat Dret penal de l'enemic , que analitzaré més avant. En aquest cas no només disminueixen les garanties, sinó que aquestes desapareixen al entendre que les persones que cometen aquests delictes no són ciutadans i per tant no són titulars de drets.

En resum, en el context de la societat del risc, no hi ha dubte que ha arrelat aquesta nova concepció del Dret penal. Una concepció no tant encaminada a una instrumentalització del control formal, com seria d'esperar, sinó a protegir la confiança dels ciutadans en el funcionament del sistema i a partir d'això assegurar el desenvolupament de la personalitat. Com ja hem vist més amunt, l'existència d'un Dret penal de tres velocitats lesiona directament els límits de l'estat democràtic, pel qual resulta capital el principi d'igualtat @corcoy_bidasolo_limites_2004. No obstant això, s'ha de dir que el Dret Penal a diferents velocitats, si més no a dos velocitats, és un tret característic de la política criminal europea del segle XX. Sistemes penals com ara l'italià, l'alemany, el portuguès i el francès, estan farcits de legislació penal especial #footnote("S'anomena legislació penal especial a aquella que no està continguda en el codi penal, obrint la porta a consideracions i especificacions que van més enllà dels principis generals continguts al codi penal, facilitant el dret penal a diferents velocitats i anant potencialment en perjudici del principi d'igualtat."). Per exemple, en el cas italià hi ha uns cinc-cents delictes al codi penal i vora cinc mil fora d'ell @donini_escenarios_2004, 2004 .

Al moment d'escriure el present treball (darrer trimestre de 2012), el govern espanyol ha aprovat el que molts no han dubtat a anomenar com al "_Codi Penal més dur de la democràcia_". Entre les mesures més repressives destaca la instauració de la pena de presó permanent revisable, o com es coneix popularment, cadena perpètua revisable. A més a més, introdueix una altra mesura privativa de llibertat nova, com és la denominada custòdia de seguretat, una mesura que permetrà allargar les condemnes de convictes que es considere que encara són perillosos, fins a 10 anys més. Però el que més em crida l'atenció,  perquè afecta directament a la penalització de la transmissió de missatges, és que s'introdueix un nou delicte que castiga la difusió de missatges mitjançant les xarxes socials, que "_inciten al les alteracions d'ordre públic_". Amb una afirmació tan poc concreta, no és d'estranyar que molts juristes estiguen preocupats per la inseguretat jurídica que això comporta, ja que es dóna a múltiples interpretacions. Penalitzar conductes com aquesta poden interpretar-se com la deslegitimació de qualsevol missatge que contravinga al poder dominant, fins al punt extrem de castigar-lo penalment.

Un informe recent del Consejo General del Poder Judicial (CGPJ) subratlla la dubtosa constitucionalitat d'algunes d'aquestes mesures, i destaca per exemple que la pena de presó permanent revisable no va entrar en vigor en un dels períodes més repressius que s'han viscut a l'estat espanyol, la dictadura del general Franco. També destaca que aquesta pena, en tant que potencialment il·limitada, entra en conflicte amb el principi de reinserció social que se li suposa a qualsevol pena, la finalitat de les quals no és altra que facilitar la rehabilitació del  delinqüent i la seua reincorporació a la societat. Si bé és cert, com veurem al capítol dedicat al Dret Penal de l'enemic, hi ha determinats actors als que se'ls dóna la consideració de "_no persones_", per tant no xoca la pretensió d'ignorar aquest principi de reinserció, ja que aquesta reinserció estaria prevista per als "_ciutadans_" i no per als "_enemics_" de la societat.
Tot això dóna una idea clara de fins a quin punt el Dret Penal està avançant i ocupant el terreny que podrien ocupar, per exemple, les mesures socials, d'un caire més preventiu.

=== Llibertat vs Seguretat

Podem considerar que un increment de la seguretat ciutadana implica una major llibertat per a les persones, en tant que fa disminuir els riscos presents a la nostra societat del risc. En canvi, podem considerar que un increment de la seguretat ciutadana va aparellada a un decrement de les llibertats individuals. Aquesta darrera posició és la mantinguda per la majoria de la doctrina espanyola i alemanya.

#cite(<buergo_derecho_2001>, form: "prose") es pronuncia a favor de resoldre el conflicte entre llibertat i seguretat en favor de la primera, és a dir, optant per un model garantista front a un model preventiu. En la seua opinió es tracta d'una decisió de caràcter ètic-polític o moral.
Altres autors com #cite(<gomez_martin_libertad_2004>, form: "prose") aposten per la tesi de que llibertat i seguretat no són constructes incompatibles. Per a que l'individu puga organitzar-se amb plena llibertat ho ha de fer en un context de seguretat. Es tracta per tant de trobar l'equilibri entre ambdós conceptes.

En qualsevol cas, aquest equilibri es presenta des d'una perspectiva dels drets i llibertats individuals, de manera que l'Estat ha de garantir la protecció de la llibertat individual, de manera que l'exercici de la llibertat d'un individu no perjudique l'exercici de llibertat d'un altre. Però es tracta també, d'aplicar el principi d'intervenció mínima o d'última ratio. Per tant, des d'aquesta perspectiva dogmàtica no es contemplarien els delictes de caràcter simbòlic, ja que no perjudiquen l'exercici de les llibertats individuals i suposen un excés intervencionista del Dret Penal. Dit d'un altra manera, des del punt de vista del principi d'intervenció mínima, cremar una foto o realitzar una caricatura, deurien de quedar de la intervenció penal.

=== Dret Penal simbòlic

Els politòlegs, sociòlegs i criminòlegs nord-americans ja des de la dècada dels seixanta han constatat que la política no és només qüestió de poder i interessos, sinó que també inclou la provisió i defensa de símbols: processos de "_elaborating symbols_" i "_summarizing symbols_" (els quals tenen també un potencial emotiu i manipulatiu) o l'eliminació i concreció dels símbols (els quals tenen només una relació vaga amb la realitat preexistent, i amb això desenvolupen una capacitat de crear una nova realitat aparent i fictícia) @hassemer_derecho_1995.
No existeix un consens dogmàtic sobre la definició de Dret penal simbòlic, però totes les definicions van en la línia d'una oposició entre la "_realitat_" i "_l'aparença_", entre allò "_manifest_" i allò "_latent_" entre allò que "_vertaderament es vol_" i allò "_altrament aplicat_".@hassemer_derecho_1995.

Podem considerar que tots el delictes contenen, en major o menor mesura, una càrrega simbòlica. Així, inclús una redacció tan asèptica com la del delicte d'homicidi, comporta l'esperança preventiva d'enfortir el respecte a la vida humana. De la mateixa manera el Codi penal també ha estat un instrument de control de les dones, de la seva sexualitat i de la seva capacitat reproductora. Quan el 1963 s'elimina la figura penal de l'uxoricidi, el legislador va argumentar la seva desaparició perquè es podia arribar a la mateixa pena (desterrament de l'home que hagués matat la seua dona per haver-la trobat mantenint relacions sexuals amb un altre home) amb el joc de les eximents i eximents incompletes ja existents. És a dir, que malgrat el valor suprem de la vida, el legislador no es qüestionava l'antijuridicitat de l'acció.

Dret penal simbòlic, conclou #cite(<hassemer_derecho_1995>, form: "prose"), "_és un Dret penal en el qual les funcions latents predominen sobre les manifestes_". En el cas objecte del present treball, el delicte d'injúries a la corona pretén protegir el dret a l'honor i a la intimitat de les persones que formen part de la família reial, quan en realitat ja existeixen altres articles que protegeixen el dret a l'honor i a la intimitat de qualsevol persona. Per tant es lògic pensar que aquest delicte persegueix altres funcions latents, com poden ser l'absència de debat sobre el règim monàrquic, el blindatge de la figura del rei i de la seua família i donar-los un aura d'intocables i d'inqüestionables.

En definitiva, el legislador hauria de castigar només aquells comportaments que amenacen un bé jurídic; els actes que només atempten a la moral, a valors socials o contra el sobirà haurien d'excloure's del catàleg de delictes @hassemer_derecho_1995.

Durant segles, els qui ostenten el poder han tractat de controlar els dissidents. La manera més clàssica de fer-ho és la criminalització dels actes de protesta i per extensió, la criminalització de les persones que protesten contra el poder, entenent ací el poder amb el sentit que li donen autors com Teun Van Dijk com  a dominació i control. Si posem el focus per un instant als EUA, ens trobem amb una societat, certament, distinta a la nostra. Podríem dir que la ciutadania ha vist tradicionalment a l'Estat com a l'enemic natural de la llibertat. Per això allí la norma general és que els judicis es porten a terme mitjançant un jurat popular, mentre que a l'estat espanyol aquest procediment és excepcional. La primera esmena de la constitució dels EUA diu que el Congrés no farà cap llei que restringisca la llibertat d'expressió #footnote("Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.").

Tot un clàssic pel que fa a la representació de la llibertat d'expressió als EUA és el fet que la crema de la bandera d'aquest país és un fet que escapa del control penal de l'estat. Les corrents conservadores han intentat introduir a la seua constitució la penalització de la crema de la bandera americana en nombroses ocasions tal i com assenyala #cite(<fiss_efecto_1996>, form: "prose"). En canvi, tots aquests intents han topat una i altra vegada amb el rebuig dels liberals i aquesta acció roman despenalitzada seguint amb l'esperit liberal de la seua constitució. Inclús quan s'ha imposat la corrent conservadora, com per exemple en la dècada dels 30-40, quan era obligatòria la salutació a la bandera a les escoles, la comunitat de testimonis de Jehovà es va oposar a fer-ho (per motius religiosos) i al Tribunal Suprem no li va quedar altre remei que acceptar l'objecció de consciència per tal de no penalitzar a aquesta comunitat @flowers_pledging_2011. És un exemple més de com una oposició ferma a un acte de violència simbòlica per part de l'estat (l'obligació de fer la salutació a la bandera) quedava fora del dret penal ja en aquells anys.


=== Dret Penal de l'Enemic

El jurista alemany Ghunter Jakobs va introduir el concepte de Dret Penal de l'Enemic, cap a l'any 1985, i posteriorment va ser desenvolupat per ell mateix i per tot un seguit de juristes que han continuat la seua doctrina @jakobs_estudios_1997. Si bé és cert que una àmplia majoria de la doctrina no comparteix les bases del discurs teòric doctrinal que sustenta aquesta corrent, resulta evident l'existència d'un corpus legislatiu específic per als "_enemics_" @martin_consideraciones_2005.

La clau per a entendre en què consisteix el Dret Penal de l'Enemic rau en que per a aquesta corrent doctrinal el Dret Penal resulta eficaç i per tant s'ha d'aplicar al "_ciutadans_". Però resulta ineficaç contra aquells que estan en contra de la convivència pacífica als que qualifiquen "_d'enemics_" (de la societat). Es tracta per tant d'una "_legislació que s'aplica a les no-persones_" @martin_consideraciones_2005.

La pròpia utilització del terme enemic, evoca tot un seguit de significats negatius que recorden a la terminologia bèl·lica, però que al mateix temps ajuda a entendre la lògica que apliquen els legisladors a l'hora de confeccionar normes penals sota aquest prisma. Les principals característiques d'una norma que segueix la doctrina del Dret Penal de l'Enemic segons arreplega el catedràtic de Dret Penal #cite(<martin_consideraciones_2005>, form: "prose") són:

- Anticipació de la punibilitat d'actes preparatoris de fets futurs. Seria el cas, per exemple, de la "_col·laboració_" amb banda armada, o apologia del terrorisme. Encara que aquesta col·laboració es materialitze únicament en el fet de pertànyer a una organització cultural juvenil amb dèbils lligams d'alguns membres amb activitats terroristes.
- Desproporcionalitat de les penes. Manifestada en que el fet d'haver participat en actes preparatoris, no comporta una disminució de la pena respecte a la participació en fets consumats (com ocorre amb la resta de delictes). I d'altra banda en el fet de la desproporció de la pena rebuda respecte d'altres conductes similars, únicament pel fet de pertànyer a una banda terrorista (és a dir, amb la consideració d'enemic).
- Restricció de garanties i drets processals. Es redueixen considerablement les exigències de licitud i admissibilitat de la prova, s'introdueixen mesures d'intervenció de les comunicacions, d'investigació secreta, mesures d'incomunicació, s'amplien els terminis de detenció policial i el que resulta més xocant, des d'un plànol teòric, es justifica la utilització de la tortura.
- Mesures restrictives en la legislació penitenciaria. Per exemple, enduriment de les condicions de classificació dels interns o ampliació dels requisits per a l'accés a la llibertat condicional, com és l'exemple de la coneguda Doctrina Parot #footnote("La sentència del Tribunal Suprem espanyol, de 28 de febrer de 2006, denega l'acceptació de recursos d'excarceració a presos que no hagen complert la condemna íntegrament, en el cas que sigui de 30 o més anys de presó. El que en la pràctica s'aplica a condemnats per Terrorisme.").

Des d'aquesta perspectiva, el delinqüent té la consideració d'un "_tumor cancerigen, que per tant, ha de ser extirpat del cos de la societat_" @martin_consideraciones_2005. La mera existència d'un Dret Penal de l'Enemic diferenciat del Dret Penal "_ordinari_", implica que aquest Dret Penal està fora del marc i dels principis generals que regeixen el dret, en tant que els autors d'aquest tipus de delictes son considerats com a no-persones i per tant no se'ls pot aplicar el dret penal ordinari, que està destinat a les persones.

Totes aquestes consideracions sobre Dret Penal de l'Enemic, juntament amb la creixent expansió del Dret Penal, i especialment del Dret Penal Simbòlic, em fan pensar que el tractament del delicte d'injúries a la corona, s'acosta perillosament a la doctrina del Dret Penal de l'Enemic, i és una de les qüestions que tractaré d'analitzar.

=== El codi penal espanyol

La principal manifestació del que resulta la política criminal d'un estat és el seu codi penal. El legislador espanyol ha optat per incloure la major part de la normativa penal en el codi penal, que no és altra cosa que un catàleg de conductes i càstigs. Què queda dins i què queda fora de la tutela penal, així com la determinació de les penes i la  gradació d'aquestes, és un criteri que entra estrictament dins de l'àmbit de la política.

Dins del codi penal espanyol vigent @boe_ley_1995 ens trobem amb un títol dedicat als delictes contra la Constitució espanyola. Dins d'aquest títol tenim tot un seguit de capítols que contenen distints delictes: Rebel·lió, delictes contra la Corona, delictes contra les institucions de l'Estat i la divisió de poders, usurpació d'atribucions, delictes relatius a l'exercici de drets fonamentals i llibertats públiques, delictes comesos per funcionaris públics contra les garanties constitucionals, delictes comesos per funcionaris públics contra altres drets individuals i, finalment, ultratges a Espanya.

No és la pretensió d'aquest treball entrar en detall a l'anàlisi de cadascun d'aquests delictes. Si més no, em centraré en la secció titulada "_delictes contra la Corona_". Aquesta secció conté 7 articles que castiguen conductes qualitativament molt diferents, que van des de l'homicidi de la persona del rei o d'algun membre de la família reial, a conductes que es castiguen pel simple fet de que presumiblement posen en perill certs valors @mateu_reflexiones_2001. Concretament analitzaré únicament els discursos que legitimen la política criminal, continguda als articles 490 i 491, per considerar que existeix una desproporció entre la conducta i el càstig previst.

L'article 485 castiga "_el que matara al Rei, o a qualsevol dels seus ascendents o descendents, a la Reina consort o al consort de la Reina, al Regent o a algun membre de la Regència, o al Príncep hereu de la Corona(...)_" @boe_ley_1995 .

L'article 486 castiga "_el que causara al Rei, o a qualsevol dels seus ascendents o descendents, a la Reina consort o al consort de la Reina, al Regent o a algun membre de la Regència, o al Príncep hereu de la Corona, lesions(...)_" @boe_ley_1995 .

L'article 487 castiga "_el que privara el Rei, o a qualsevol dels seus ascendents o  descendents, a la Reina consort o al consort de la Reina, al Regent o a algun membre de la Regència, o al Príncep hereu de la Corona, de la seua llibertat personal(...)_" @boe_ley_1995 .

L'article 488 castiga "_la provocació, la conspiració i la proposició per als delictes previstos en els articles anteriors(...)_" @boe_ley_1995 .

L'article 489 castiga "_el que amb violència o intimidació greu obligara les persones referides en els articles anteriors a executar un acte contra la seua voluntat(...)_" @boe_ley_1995 .

L'article 490 castiga "_El que violara amb violència o intimidació el domicili de qualsevol de les persones mencionades en els articles anteriors(...).
(...)el que amenaçara greument a qualsevol de les persones mencionades en l'apartat anterior(...).
El que calumniara o injuriara el Rei o a qualsevol dels seus ascendents o descendents, a la Reina consort o al consort de la Reina, al Regent o a algun membre de la Regència, o al Príncep hereu de la Corona, en l'exercici de les seues funcions o amb motiu o ocasió d'estes(...)_" @boe_ley_1995 .

I finalment, l'article 491 castiga "_Les calúmnies i injúries contra qualsevol de les persones mencionades en l'article anterior, i fora dels supòsits previstos en el mateix(...).
(...)a qui utilitzara la imatge del Rei o de qualsevol dels seus ascendents o descendents, o de la Reina consort o del consort de la Reina, o del Regent o d'algun membre de la Regència, o del Príncep hereu, de totes maneres que puga danyar el prestigi de la Corona(...)_" @boe_ley_1995 .

Els articles 490 i 491, preveuen penes de presó d'entre 6 mesos i 2 anys si l'enjudiciador considera que cremar una foto o fer una caricatura, són injúries greus a la corona. Això ens fa plantejar-nos que tanta desproporció ha de respondre a algun criteri de política criminal i té el seu encaix amb la tesi del Dret Penal de l'Enemic, per a la qual s'apliquen penes desproporcionades.
 
